argocd:
  namespace: argocd
  project: platform
  targetRevision: main

global:
  domain: "placeholder.com"

kanidm:
  enabled: false
  namespace: kanidm

dex:
  enabled: false

externalSecrets:
  enabled: true
  namespace: platform

globalSecrets:
  enabled: true

reloader:
  enabled: true
  namespace: platform

temporal:
  enabled: false
  namespace: platform

## Grafana test
grafana:
  enabled: false
  namespace: platform

cassandra:
  enabled: false
