argocd:
  namespace: argocd
  project: apps
  targetRevision: main

global:
  domain: placeholder.com
  env: prod

excalidraw:
  enabled: false

homepage:
  enabled: false

speedtest:
  enabled: false

jellyfin:
  enabled: false
