argocd:
  namespace: argocd
  project: apps
  targetRevision: main

global:
  domain: "placeholder.com"
  env: "dev"

filebrowser:
  enabled: false

dendrite:
  enabled: false
  storageClass: "local-path"
  autosign: true

element:
  enabled: false


# Playground services
memcached:
  enabled: false

cortex:
  enabled: false
  basicAuth:
    insecure: true
    secretName: "cortex-humble-tenant"

microservicesDemo:
  enabled: false

dashyLandscape:
  enabled: true

consul:
  enabled: false

nfs:
  enabled: false

yutaops:
  enabled: false
